In [5]:
from google.colab import files
import pandas as pd
import io

print("Please upload your file:")
uploaded = files.upload()

for fn in uploaded.keys():
  print(f'User uploaded file "{fn}"')

  # Assuming a CSV file, modify this if your file type is different
  try:
    df = pd.read_csv(io.StringIO(uploaded[fn].decode('utf-8')))
    print("File successfully loaded into a pandas DataFrame.")
    display(df.head())
  except Exception as e:
    print(f"Error loading file '{fn}': {e}\nPlease ensure it is a CSV file or modify the `pd.read_csv` call accordingly.")

Please upload your file:

Saving Advanced_pandas_sales_dataset.csv to Advanced_pandas_sales_dataset (1).csv
User uploaded file "Advanced_pandas_sales_dataset (1).csv"
File successfully loaded into a pandas DataFrame.

,Order_ID,Order_Date,Customer,City,Region,Product,Category,Sales,Quantity,Discount,Profit
0,1001,2024-10-01,Priya,Hyderabad,East,Mouse,Accessories,1735,7,0.00,307.52
1,1002,2024-05-03,Sneha,Kolkata,East,Monitor,Electronics,807,2,0.15,49.89
2,1003,2024-01-26,Anita,Mumbai,West,Phone,Electronics,2328,1,0.20,66.47
3,1004,2024-06-06,Sara,Pune,East,Keyboard,Accessories,3933,3,0.20,-71.66
4,1005,2024-10-15,Rahul,Bangalore,South,Monitor,Electronics,3550,2,0.20,146.30

In [6]:
df= pd.read_csv('Advanced_pandas_sales_dataset.csv')

In [7]:
df

,Order_ID,Order_Date,Customer,City,Region,Product,Category,Sales,Quantity,Discount,Profit
0,1001,2024-10-01,Priya,Hyderabad,East,Mouse,Accessories,1735,7,0.00,307.52
1,1002,2024-05-03,Sneha,Kolkata,East,Monitor,Electronics,807,2,0.15,49.89
2,1003,2024-01-26,Anita,Mumbai,West,Phone,Electronics,2328,1,0.20,66.47
3,1004,2024-06-06,Sara,Pune,East,Keyboard,Accessories,3933,3,0.20,-71.66
4,1005,2024-10-15,Rahul,Bangalore,South,Monitor,Electronics,3550,2,0.20,146.30
...,...,...,...,...,...,...,...,...,...,...,...
225,1226,2024-06-14,Anita,Ahmedabad,East,Laptop,Electronics,5647,2,0.15,662.00
226,1227,2024-04-02,Dev,Pune,South,Mouse,Accessories,1669,6,0.05,323.13
227,1228,2024-01-14,Vikas,Chennai,North,Tablet,Electronics,2682,7,0.15,119.82
228,1229,2024-09-04,Priya,Pune,East,Tablet,Electronics,2635,8,0.00,531.76
229,1230,2024-04-13,Meera,Kolkata,North,Monitor,Electronics,5087,8,0.10,416.72

In [8]:
df.head(10) #Display the first 10 rows

,Order_ID,Order_Date,Customer,City,Region,Product,Category,Sales,Quantity,Discount,Profit
0,1001,2024-10-01,Priya,Hyderabad,East,Mouse,Accessories,1735,7,0.00,307.52
1,1002,2024-05-03,Sneha,Kolkata,East,Monitor,Electronics,807,2,0.15,49.89
2,1003,2024-01-26,Anita,Mumbai,West,Phone,Electronics,2328,1,0.20,66.47
3,1004,2024-06-06,Sara,Pune,East,Keyboard,Accessories,3933,3,0.20,-71.66
4,1005,2024-10-15,Rahul,Bangalore,South,Monitor,Electronics,3550,2,0.20,146.30
5,1006,2024-07-04,Pooja,Bangalore,West,Printer,Office,3073,8,0.20,191.58
6,1007,2024-06-24,Dev,Chennai,East,Monitor,Electronics,1170,5,0.20,22.83
7,1008,2024-03-18,Kavya,Kolkata,East,Phone,Electronics,4693,7,0.05,918.49
8,1009,2024-10-31,Kavya,Ahmedabad,East,Phone,Electronics,5071,6,0.10,707.55
9,1010,2024-12-25,Pooja,Ahmedabad,North,Phone,Electronics,2711,8,0.00,477.32

In [9]:
df.info() #Display the dataset structure using info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 230 entries, 0 to 229
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Order_ID    230 non-null    int64
 1   Order_Date  230 non-null    object
 2   Customer    230 non-null    object
 3   City        230 non-null    object
 4   Region      230 non-null    object
 5   Product     230 non-null    object
 6   Category    230 non-null    object
 7   Sales       230 non-null    int64
 8   Quantity    230 non-null    int64
 9   Discount    230 non-null    float64
 10  Profit      230 non-null    float64
dtypes: float64(2), int64(3), object(6)
memory usage: 19.9+ KB

In [10]:
df.shape #Find the number of rows and columns

(230, 11)

In [11]:
df.dtypes #Identify the data types of each column

Order_ID        int64
Order_Date     object
Customer       object
City           object
Region         object
Product        object
Category       object
Sales           int64
Quantity        int64
Discount      float64
Profit        float64
dtype: object

In [12]:
df.loc[df['Sales'] >3500, ['Order_ID', 'Sales']]  #Orders where Sales > 3500

     Order_ID  Sales
3        1004   3933
4        1005   3550
7        1008   4693
8        1009   5071
10       1011   5977
..        ...    ...
219      1220   5986
222      1223   4356
223      1224   4115
225      1226   5647
229      1230   5087

[104 rows x 2 columns]

In [13]:
df.loc[(df['Region']== 'East') & (df['Sales'] > 2500), ['Order_ID']] #Orders where Region = "East" and Sales > 2500

     Order_ID
3        1004
7        1008
8        1009
13       1014
21       1022
27       1028
33       1034
34       1035
41       1042
43       1044
52       1053
55       1056
58       1059
60       1061
70       1071
71       1072
73       1074
74       1075
76       1077
81       1082
87       1088
92       1093
96       1097
98       1099
108      1109
109      1110
112      1113
113      1114
116      1117
128      1129
139      1140
141      1142
146      1147
152      1153
156      1157
171      1172
179      1180
182      1183
185      1186
187      1188
193      1194
197      1198
202      1203
207      1208
216      1217
223      1224
225      1226
228      1229

In [14]:
df.groupby('Customer')['Sales'].sum().sort_values(ascending=0).head(5)  #Q3 Customer Purchase Analysis Identify the top 5 customers based on total sales.

Customer
Nitin    59820
Raj      58416
Rahul    52291
Dev      48500
Isha     46818
Name: Sales, dtype: int64

In [15]:
df.groupby('Region')['Sales'].sum().sort_values(ascending=0).head(1) #Q4 Regional Sales Performance Calculate the total sales generated by each region.

#Then identify:

# Which region generated the highest revenue?

Region
East    232675
Name: Sales, dtype: int64

In [16]:
df

,Order_ID,Order_Date,Customer,City,Region,Product,Category,Sales,Quantity,Discount,Profit
0,1001,2024-10-01,Priya,Hyderabad,East,Mouse,Accessories,1735,7,0.00,307.52
1,1002,2024-05-03,Sneha,Kolkata,East,Monitor,Electronics,807,2,0.15,49.89
2,1003,2024-01-26,Anita,Mumbai,West,Phone,Electronics,2328,1,0.20,66.47
3,1004,2024-06-06,Sara,Pune,East,Keyboard,Accessories,3933,3,0.20,-71.66
4,1005,2024-10-15,Rahul,Bangalore,South,Monitor,Electronics,3550,2,0.20,146.30
...,...,...,...,...,...,...,...,...,...,...,...
225,1226,2024-06-14,Anita,Ahmedabad,East,Laptop,Electronics,5647,2,0.15,662.00
226,1227,2024-04-02,Dev,Pune,South,Mouse,Accessories,1669,6,0.05,323.13
227,1228,2024-01-14,Vikas,Chennai,North,Tablet,Electronics,2682,7,0.15,119.82
228,1229,2024-09-04,Priya,Pune,East,Tablet,Electronics,2635,8,0.00,531.76
229,1230,2024-04-13,Meera,Kolkata,North,Monitor,Electronics,5087,8,0.10,416.72

In [19]:
df.groupby('Product')['Quantity'].sum() #Q5 Product Performance Analysis-- Calculate the total quantity sold for each product.

Product
Headphones    115
Keyboard      110
Laptop        140
Monitor       156
Mouse         122
Phone         151
Printer       108
Tablet        150
Name: Quantity, dtype: int64

In [20]:
df.groupby('Product')['Sales'].sum().sort_values(ascending=0).head(1) #Which product appears to be the most popular?

Product
Phone    116270
Name: Sales, dtype: int64

In [23]:
df.groupby(['Region','Category'])['Sales'].sum() #Q6 Multi-Level Grouping

#Group the dataset by: Region and Category

#Calculate the total sales for each combination.

Region  Category
East    Accessories     57646
        Electronics    160907
        Office          14122
North   Accessories     62052
        Electronics     70023
        Office          26135
South   Accessories     80914
        Electronics     86690
        Office          15504
West    Accessories     64811
        Electronics     84128
        Office          21288
Name: Sales, dtype: int64

In [ ]:
#Q6- What insights can you derive from this analysis?

#Ans- Electronics is the clear revenue driver everywhere
#East region is the standout performer, driven almost entirely by Electronics
#Office is consistently the weakest category in every region
#North is the weakest overall region

In [29]:
df.pivot_table(index="Region",columns='Product',values= 'Sales',aggfunc='sum')  #Q7 Pivot Table Creation

Product  Headphones  Keyboard  Laptop  Monitor  Mouse  Phone  Printer  Tablet
Region
East          23899     10845   55568    31299  22902  39667    14122   34373
North         15450     20538    4540    14922  26064  30535    26135   20026
South         24111     23480   23029    19167  33323  18218    15504   26276
West          17159     38499   10826    18178   9153  27850    21288   27274

In [30]:
df

,Order_ID,Order_Date,Customer,City,Region,Product,Category,Sales,Quantity,Discount,Profit
0,1001,2024-10-01,Priya,Hyderabad,East,Mouse,Accessories,1735,7,0.00,307.52
1,1002,2024-05-03,Sneha,Kolkata,East,Monitor,Electronics,807,2,0.15,49.89
2,1003,2024-01-26,Anita,Mumbai,West,Phone,Electronics,2328,1,0.20,66.47
3,1004,2024-06-06,Sara,Pune,East,Keyboard,Accessories,3933,3,0.20,-71.66
4,1005,2024-10-15,Rahul,Bangalore,South,Monitor,Electronics,3550,2,0.20,146.30
...,...,...,...,...,...,...,...,...,...,...,...
225,1226,2024-06-14,Anita,Ahmedabad,East,Laptop,Electronics,5647,2,0.15,662.00
226,1227,2024-04-02,Dev,Pune,South,Mouse,Accessories,1669,6,0.05,323.13
227,1228,2024-01-14,Vikas,Chennai,North,Tablet,Electronics,2682,7,0.15,119.82
228,1229,2024-09-04,Priya,Pune,East,Tablet,Electronics,2635,8,0.00,531.76
229,1230,2024-04-13,Meera,Kolkata,North,Monitor,Electronics,5087,8,0.10,416.72

In [31]:
df.groupby('Category')['Profit'].mean() #Q8 Profitability Analysis Calculate the average profit for each product category.

Category
Accessories    410.603086
Electronics    396.462114
Office         471.938462
Name: Profit, dtype: float64

In [32]:
df.groupby('Category')['Profit'].mean().sort_values(ascending=0).head(1) #Q8 Profitability Analysis


#Which category is most profitable?

Category
Office    471.938462
Name: Profit, dtype: float64

In [44]:
df

,Order_ID,Order_Date,Customer,City,Region,Product,Category,Sales,Quantity,Discount,Profit
0,1001,2024-10-01,Priya,Hyderabad,East,Mouse,Accessories,1735,7,0.00,307.52
1,1002,2024-05-03,Sneha,Kolkata,East,Monitor,Electronics,807,2,0.15,49.89
2,1003,2024-01-26,Anita,Mumbai,West,Phone,Electronics,2328,1,0.20,66.47
3,1004,2024-06-06,Sara,Pune,East,Keyboard,Accessories,3933,3,0.20,-71.66
4,1005,2024-10-15,Rahul,Bangalore,South,Monitor,Electronics,3550,2,0.20,146.30
...,...,...,...,...,...,...,...,...,...,...,...
225,1226,2024-06-14,Anita,Ahmedabad,East,Laptop,Electronics,5647,2,0.15,662.00
226,1227,2024-04-02,Dev,Pune,South,Mouse,Accessories,1669,6,0.05,323.13
227,1228,2024-01-14,Vikas,Chennai,North,Tablet,Electronics,2682,7,0.15,119.82
228,1229,2024-09-04,Priya,Pune,East,Tablet,Electronics,2635,8,0.00,531.76
229,1230,2024-04-13,Meera,Kolkata,North,Monitor,Electronics,5087,8,0.10,416.72

In [48]:
df.groupby('Discount')['Profit'].mean().sort_index() #Q9 Discount Impact Study

# Analyze the relationship between discount and profit.

# Tasks:

# Calculate the average profit for each discount level

Discount
0.00    751.210588
0.05    531.368039
0.10    346.460513
0.15    237.191400
0.20     90.026923
Name: Profit, dtype: float64

In [ ]:
# #Q9 Discount Impact Study-- Identify whether higher discounts lead to lower profit

# Business insight this reveals

# There's a clear, strong inverse relationship between discount and profit: as discount increases from 0% to 20%, average profit drops steadily and sharply — from ~₹751 at no discount down to just ~₹90 at a 20% discount. That's roughly an 88% drop in average profit between the lowest and highest discount tiers.

In [40]:
filtered = df[df['Sales'] > 3000] #Q10 End-to-End Data Wrangling Task


# Filter the dataset where Sales > 3000

In [42]:
grouped= filtered.groupby(['Region','Product'])['Sales'].sum()
print(grouped) #Q10 End-to-End Data Wrangling Task
#Step 2 & 3: Group by Region and Product, calculate total sales

Region  Product
East    Headphones    14469
        Keyboard       9642
        Laptop        44096
        Monitor       16420
        Mouse         19000
        Phone         29500
        Printer        3696
        Tablet        29229
North   Headphones     5326
        Keyboard      15653
        Laptop         4540
        Monitor        5087
        Mouse         22209
        Phone         24670
        Printer       17185
        Tablet         3392
South   Headphones    10026
        Keyboard      19249
        Laptop        17950
        Monitor       14921
        Mouse         26928
        Phone         18218
        Printer       14143
        Tablet        19613
West    Headphones    13898
        Keyboard      33380
        Laptop         5922
        Monitor       14354
        Mouse          3511
        Phone         15653
        Printer       12648
        Tablet        17185
Name: Sales, dtype: int64

In [43]:
Pivote= filtered.pivot_table(index='Region',columns='Product',values='Sales',aggfunc='sum')
print(Pivote) #Q10 End-to-End Data Wrangling Task
#Step 4: Create a pivot table

Product  Headphones  Keyboard  Laptop  Monitor  Mouse  Phone  Printer  Tablet
Region
East          14469      9642   44096    16420  19000  29500     3696   29229
North          5326     15653    4540     5087  22209  24670    17185    3392
South         10026     19249   17950    14921  26928  18218    14143   19613
West          13898     33380    5922    14354   3511  15653    12648   17185

In [ ]:
# Business Insights

# East dominates high-value sales overall — East leads with 1,66,052 in total high-value Sales (Sales > 3000), well ahead of South (1,41,048), West (1,16,551), and North (98,062). This is driven overwhelmingly by Laptops (44,096) — the single biggest cell in the entire table.

# Laptops and Phones are the premium-ticket products — Phones bring in the highest overall total (88,041) across regions, followed closely by Keyboard (77,924) and Laptop (72,508). Since we filtered for Sales > 3000, this tells you these categories most frequently produce large individual transactions — likely bulk orders or premium-priced units.

# Regional product strengths differ sharply, suggesting localized demand:

# East is the clear Laptop hub (44,096 — more than double any other region's Laptop total)
# West stands out in Keyboards (33,380 — the highest single Keyboard figure by far)
# North leads in Mouse sales (22,209) despite being the weakest region overall
# South shows the most balanced spread across all products — no single category dominates

# Printers and Headphones are consistently the weakest high-value categories across nearly every region, suggesting these products rarely generate large single transactions (likely lower unit prices, so they don't clear the 3000 threshold often).

# Recommendation angle: East's inventory/marketing strategy for Laptops seems to be working — worth investigating what's different there (pricing, customer base, promotions) and considering replicating it in North, which is comparatively lagging in nearly every product category.